_extends: .github

repository:

  #─────────────────────────────────────────────────────────────────────────────
  # "About" section (on Home Page)
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # A short description of the repo
  # MUST BE A SINGLE LINE
  description: Template repo for publishing NuGet packages

  # A URL with more information about the repo
  homepage:

  # A comma-separated list of topics to set on the repo
  # See https://github.com/topics
  topics: dotnet, csharp, nuget, template-repo

  #─────────────────────────────────────────────────────────────────────────────
  # Settings → General
  # https://github.com/repository-settings/app/blob/master/docs/plugins/repository.md
  # https://docs.github.com/en/rest/repos/repos#update-a-repository
  #─────────────────────────────────────────────────────────────────────────────

  # The name of the repo
  name: .template-NuGet

#───────────────────────────────────────────────────────────────────────────────
# Settings → Rules → Rulesets
# https://github.com/repository-settings/app/blob/master/docs/plugins/rulesets.md
# https://docs.github.com/en/rest/repos/rules#update-a-repository-ruleset
# https://github.com/github/ruleset-recipes
#───────────────────────────────────────────────────────────────────────────────
rulesets:

  - name: Status checks must pass
    target: branch
    enforcement: disabled
    bypass_actors:
      - actor_id: 5 # Repository admin
        actor_type: RepositoryRole
        bypass_mode: pull_request
    conditions:
      ref_name:
        include: [~DEFAULT_BRANCH]
        exclude: []
    rules:
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: true
          do_not_enforce_on_create: true
          required_status_checks:
            - context: Analyze (actions)
              integration_id: 15368 # GitHub Actions
            - context: Analyze (csharp)
              integration_id: 15368 # GitHub Actions
            - context: Build and Test
              integration_id: 15368 # GitHub Actions
            - context: codecov/patch
              integration_id: 254 # Codecov
            - context: codecov/project
              integration_id: 254 # Codecov
      - type: code_scanning
        parameters:
          code_scanning_tools:
            - tool: CodeQL
              security_alerts_threshold: high_or_higher
              alerts_threshold: errors

#───────────────────────────────────────────────────────────────────────────────
# Issues → Labels
# https://github.com/repository-settings/app/blob/master/docs/plugins/labels.md
#───────────────────────────────────────────────────────────────────────────────
labels:

  # Dependabot Ecosystems
  # https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories
  # (each uses its own marketing color)

  - name: .NET SDK
    color: "#522ed1"
    description: Updates to the required .NET SDK

  - name: NuGet
    color: "#07497f"
    description: Updates to NuGet packages
