# See https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
    notify_error: true

coverage:
  precision: 2
  round: down
  range: '90...95'
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: failure
        if_ci_failed: error
    patch:
      default:
        target: 95%
        threshold: 2%
        if_ci_failed: error
    changes: false

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: condensed_header,header,reach,diff,flags,components,condensed_files,files,condensed_footer,footer
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
