name: ✨ Feature request
description: Suggest an idea or enhancement
assignees: [TaffarelJr]
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to help us provide more value! 🤗
        Please see
        [`CONTRIBUTING.md`](https://github.com/TaffarelJr/.template-nuget-package/blob/main/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion)
        for more information on writing a good enhancement suggestion.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: >
        Please make sure these options have been tried
        before submitting a new idea or enhancement suggestion.
      options:
        - label: >
            I've searched the
            [Documentation](https://github.com/TaffarelJr/.template-nuget-package/tree/main/docs)
            and [Wiki](https://github.com/TaffarelJr/.template-nuget-package/wiki)
            for information on this topic,
            and I'm sure it's not currently available.
          required: true
        - label: >
            I've searched and/or posted in the
            [Discussions](https://github.com/TaffarelJr/.template-nuget-package/discussions)
            about this enhancement.
          required: true
        - label: >
            The enhancement is appropriate
            and in-line with the goals of this project,
            and will benefit the majority of users.
          required: true
        - label: >
            I've searched the existing
            [Issues](https://github.com/TaffarelJr/.template-nuget-package/issues)
            and this enhancement has not been suggested yet.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the purpose and value of the enhancement.
      placeholder: Description
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: API Proposal
      description: Please provide the specific API signature you're proposing.
      placeholder: API proposal
      value: |
        ```csharp
        namespace MyProject;

        public class MyClass<T>
        {
            public void Foo(T item);
        }
        ```
    validations:
      required: true

  - type: textarea
    id: usage
    attributes:
      label: API Usage
      description: >
        Please provide code examples that demonstrate
        how the proposed API changes are meant to be used.
        This will help determine whether the API has the right "shape"
        to be functional, performant, and usable.
      placeholder: API usage
      value: |
        ```csharp
        var c = new MyClass<int>();
        c.Foo(42);
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Designs
      description: >
        Please provide alternative designs, if applicable.
        For example instead of providing new APIs,
        an option might be to change the behavior of an existing API.
      placeholder: Alternative designs
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: >
        Please mention any risks that the API proposal might entail
        (to the best of your knowledge) -
        such as breaking changes, performance regressions, etc.
      placeholder: Risks
    validations:
      required: false
